config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cafes#index'
  resources :users, only: [:show, :edit, :update]
  resources :cafes do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :purpose
  belongs_to :prefecture

  with_options presence: true do
    validates :image
    validates :name
    validates :address
    validates :recommend, length: { maximum: 100 }

    with_options numericality: { other_than: 1, message: "can't be blank" } do
      validates :purpose_id
      validates :prefecture_id
    end
  end

  belongs_to :user
  has_many :comments, dependent: :destroy
  # has_many :likes
  has_many_attached :images
  has_one_attached :image

  def self.search(_search)
    Cafe.all
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cafe
  has_one_attached :image

  validates :text, presence: true, unless: :was_attached?
  def was_attached?
    image.attached?
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '----' },
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :cafes
end

app/models/purpose.rb
class Purpose < ActiveHash::Base
  self.data = [
    { id: 1, name: '----' },
    { id: 2, name: 'コーヒー' },
    { id: 3, name: '紅茶' },
    { id: 4, name: 'スイーツ' },
    { id: 5, name: 'オシャレ' }
  ]

  include ActiveHash::Associations
  has_many :cafes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
  end
  validates :profile, length: { maximum: 100 }

  has_many :cafes
  has_many :comments
  # has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
    devise_parameter_sanitizer.permit(:accunt_update, keys: [:nickname, :profile])
  end
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_user
  before_action :set_cafe, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @cafe = Cafe.new
  end

  def create
    if params[:password] == '1234'
      @cafe = Cafe.create(cafe_params)
      if @cafe.save
        redirect_to root_path
      else
        render :new
      end
    else
      render :new
    end
  end

  def search
    set_prefecture
    set_purpose
  end

  def show
    @comment = Comment.new
    @comments = @cafe.comments.includes(:user)
    @comments = @cafe.comments.order(created_at: 'DESC')
  end

  def edit
    @image = @cafe.image
  end

  def update
    if @cafe.update(cafe_params)
      redirect_to cafe_path
    else
      render :show
    end
  end

  def destroy
    @cafe.destroy
    redirect_to root_path
  end

  private

  def cafe_params
    params.permit({ images: [] }, :name, :address, :URL, :recommend, :purpose_id, :prefecture_id, :password,
                  :id).merge(user_id: current_user.id)
  end

  def set_user
    @user = current_user
  end

  def set_cafe
    @cafe = Cafe.find(params[:id])
  end

  def move_to_index
    redirect_to root_path if current_user.id != @cafe.user_id
  end

  def set_prefecture
    if params[:region] == '1'
      @cafe = Cafe.where(prefecture_id: [14])
      @region = '東京'
    elsif params[:region] == '2'
      @cafe = Cafe.where(prefecture_id: [2])
      @region = '北海道'
    elsif params[:region] == '3'
      @cafe = Cafe.where(prefecture_id: [3..8])
      @region = '東北地方'
    elsif params[:region] == '4'
      @cafe = Cafe.where(prefecture_id: [9..15])
      @region = '関東地方'
    elsif params[:region] == '5'
      @cafe = Cafe.where(prefecture_id: [16..24])
      @region = '中部地方'
    elsif params[:region] == '6'
      @cafe = Cafe.where(prefecture_id: [25..31])
      @region = '関西地方'
    elsif params[:region] == '7'
      @cafe = Cafe.where(prefecture_id: [32..36])
      @region = '中国地方'
    elsif params[:region] == '8'
      @cafe = Cafe.where(prefecture_id: [37..40])
      @region = '四国地方'
    elsif params[:region] == '9'
      @cafe = Cafe.where(prefecture_id: [41..48])
      @region = '九州地方'
    elsif params[:purpose_id] && params[:prefecture_id]
      @cafe = Cafe.where(purpose_id: params[:purpose_id], prefecture_id: params[:prefecture_id])
    end
  end

  def set_purpose
    if params[:genre] == '1'
      @cafe = Cafe.where(purpose_id: [2])
      @purpose = 'コーヒー'
      @purpose_id = 2
    elsif params[:genre] == '2'
      @cafe = Cafe.where(purpose_id: [3])
      @purpose = '紅茶'
      @purpose_id = 3
    elsif params[:genre] == '3'
      @cafe = Cafe.where(purpose_id: [4])
      @purpose = 'スイーツ'
      @purpose_id = 4
    elsif params[:genre] == '4'
      @cafe = Cafe.where(purpose_id: [5])
      @purpose = 'オシャレ'
      @purpose_id = 5
    elsif params[:purpose_id] && params[:prefecture_id]
      @cafe = Cafe.where(purpose_id: params[:purpose_id], prefecture_id: params[:prefecture_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @cafe = Cafe.find(params[:cafe_id])
    @comment = Comment.create(comment_params)
    redirect_to cafe_path(@cafe.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :image, :cafe_id).merge(user_id: current_user.id, cafe_id: params[:cafe_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @cafe = @user.cafes
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      redirect_to user_path
    else
      render :edit
    end
  end

  def user_params
    params.permit(:nickname, :email, :password, :profile)
  end

  def move_to_index
    redirect_to root_path if current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cafes/edit.html.erb
<%= render "shared/header" %>

<%# cssは cafes/newを併用 %>
<%= form_with model: @cafes, url: cafe_path, class:"new-cafe", method: :patch, local: true do |f| %>

  <h2>カフェ情報 編集</h2>

  <div class="form-image">
    <p>画像のアップロード<span>※必須</span></p>
    <%= f.file_field :image, id:"cafe-image" %>
  </div>
  <div class="form-cafe">
    <label class="form-text">名前</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.text_field :name, value: @cafe.name, class:"input-default", id:"name" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">住所</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.text_field :address, value: @cafe.address, class:"input-default", id:"address" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">URL</label>
    <div class="field">
      <%= f.text_field :URL, value: @cafe.URL, class:"input-default", id:"URL" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">おすすめポイント！</label>
    <span class="indispensable">※必須</span>
    <div class="area">
      <%= f.text_area :recommend, value: @cafe.recommend, class:"input-area-default", id:"recommend" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">目的</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.collection_select(:purpose_id, Purpose.all, :id, :name, {selected: @cafe.purpose.id}, {class:"select-box", id:"cafe-purpose"}) %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">地域</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {selected: @cafe.prefecture.id}, {class:"select-box", id:"cafe-prefecture"}) %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "変更する", class:"submit-cafe" %>
  </div>
<% end %>

app/views/cafes/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="wrapper">
    <div class="side-image">
      <%= image_tag "top-sweets.png", class: "top-img" %>
      <%= image_tag "top-coffee.png", class: "bottom-img" %>
    </div>
    <div class="slide" id="makeImg">
      <%= image_tag "sepia.640.png", class:"img" %>
      <%= image_tag "tea.sepia.png", class:"img" %>
      <%= image_tag "sweets.sepia.png", class:"img" %>
      <%= image_tag "cafe.sepia.png", class:"img" %>
    </div>
  </div>
  <div class="contents">
    <h1>あなたはまだ出会っていないかもしれない...<br>運命とも思える<span>最高の一杯に</span></h1>
    <h2>目的</h2>
    <ul div class="purpose">
        <li><%= link_to 'コーヒー', search_cafes_path(genre: 1), class: "genre", method: :get %></li>
        <li><%= link_to '紅茶', search_cafes_path(genre: 2), class: "genre", method: :get %></li>
        <li><%= link_to 'スイーツ', search_cafes_path(genre: 3), class: "genre", method: :get %></li>
        <li><%= link_to 'オシャレ', search_cafes_path(genre: 4), class: "genre", method: :get %></li>
    </ul>
    <h2>地域</h2>
      <ul div class="place">
        <li><%= link_to "東京",search_cafes_path(region: 1), class:"btn-region", method: :get %></li>
        <li><%= link_to "北海道",search_cafes_path(region: 2), class:"btn-region", method: :get %></li>
        <li><%= link_to "東北",search_cafes_path(region: 3), class:"btn-region", method: :get %></li>
        <li><%= link_to "関東",search_cafes_path(region: 4), class:"btn-region", method: :get %></li>
        <li><%= link_to "中部",search_cafes_path(region: 5), class:"btn-region", method: :get %></li>
        <li><%= link_to "関西",search_cafes_path(region: 6), class:"btn-region", method: :get %></li>
        <li><%= link_to "中国",search_cafes_path(region: 7), class:"btn-region", method: :get %></li>
        <li><%= link_to "四国",search_cafes_path(region: 8), class:"btn-region", method: :get %></li>
        <li><%= link_to "九州",search_cafes_path(region: 9), class:"btn-region", method: :get %></li>
  </div>
</div>

<div class="footer">
  <%= image_tag "plant-698637_640.jpg", class:"footer-img" %>
  <div class="message">
    <h2>カフェに求めるものはなんですか？<br><span>あなたにも運命の出会いがありますように...</span></h2>
    <%= image_tag "coffee.girl.png", class:"footer-girl" %>
  </div>
</div>

app/views/cafes/new.html.erb
<%= render "shared/header" %>

<%= form_with model: @cafes, url: cafes_path, class:"new-cafe", local: true do |f| %>

  <h2>新規カフェ登録</h2>

  <div class="form-image">
    <p>画像のアップロード<br>カフェの外観がわかる画像があればお願いします！<span>※必須</span></p>
    <%= f.file_field :image, id:"cafe-image" %>
  </div>
  <div class="form-cafe">
    <label class="form-text">名前</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.text_field :name, class:"input-default", id:"name" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">住所</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.text_field :address, class:"input-default", id:"address" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">URL</label>
    <div class="field">
      <%= f.text_field :URL, class:"input-default", id:"URL" %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">おすすめポイント！</label>
    <span class="indispensable">※必須</span>
    <div class="area">
      <%= f.text_area :recommend, class:"input-area-default", id:"recommend" %>
    </div>
  </div>
    <div class="form-image">
    <p>その他画像（複数選択可能）</p>
    <%= f.file_field :images, multiple: true %>
  </div>
  <div class="form-cafe">
    <label class="form-text">目的</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.collection_select(:purpose_id, Purpose.all, :id, :name, {}, {class:"select-box", id:"cafe-purpose"}) %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">地域</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"cafe-prefecture"}) %>
    </div>
  </div>
  <div class="form-cafe">
    <label class="form-text">パスワード</label>
    <span class="indispensable">※必須</span>
    <div class="field">
      <%= f.text_field :password, class:"input-default", id:"password" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "投稿する", class:"submit-cafe" %>
  </div>
<% end %>

app/views/cafes/search.html.erb
<%= render "shared/header" %>

<div class="cafe-all">
  <div class="search-header">
    <h2>カフェ一覧</h2>

      <div class="prefecture-search">
        <%= render "shared/prefecture" %>
        <%= render "shared/purpose" %>
     </div>
  </div>

  <h3 class="region"><%= @region %></h3>
  <div class="cafe-order">
    <% @cafe.each do |cafe| %>
      <div class="cafe-search">
        <%= link_to cafe_path(cafe) do %>
          <%= image_tag cafe.image, class:"search-image" %>
          <div class="search-name">
            『<%= cafe.name %>』
          </div>
          <div class="search-purpose">
          目的:  <%= cafe.purpose.name %>
          </div>
          <div class="search-region">
          地域:  <%= cafe.prefecture.name %>
          </div>
          <div class="search-address">
          住所:  <%= cafe.address %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cafes/show.html.erb
<%= render "shared/header" %>

<div class="cafe-detail">
  <%= image_tag @cafe.image, class:"cafe-image" %>
    <div class="cafe-name">
      名前:  『<%= @cafe.name %>』
    </div>
    <div class="cafe-address">
      住所:  <%= @cafe.address %>
    </div>
    <div class="cafe-URL">
      <%= @cafe.URL, placeholder="URL" %>
    </div>
    <div class="cafe-purpose">
      目的:  <%= @cafe.purpose.name %>
    </div>
    <div class="point">おすすめポイント！</div>
    <div class="cafe-recommend">
      <%= @cafe.recommend %>
    </div>
    <div class="cafe-images">
    <%= form_with model: @cafes, url: cafe_path, method: :put, class:"images-cafe", local: true do |f| %>
       <% @cafe.images.each do |img| %>
        <%= image_tag img, multiple: true, class:"all-images" %>
      <% end %>
    </div>
    <div class="form-image">
      <p>画像の投稿</p>
      <%= f.file_field :images, direct_upload: true, multiple: true, id:"images-cafe" %>
      <%= f.submit "写真を送る", class:"submit-cafe" %>
    </div>
    <% end %>

   <div class="cafe-user">
      投稿者:  <%= link_to "#{@cafe.user.nickname}", user_path(@cafe.user_id), class:"post-user" %>
      <% if current_user.id == @cafe.user_id %>
        <div class="edit-btn">
          <%= link_to "編集する", edit_cafe_path, class:"cafe-edit" %>
          <%= link_to "削除する", cafe_path, method: :delete, class:"cafe-destroy" %>
        </div>
      <% end %>
    </div>
</div>

<% if user_signed_in? %>
<div class="comment">
  <h2>コメント</h2>
  <div class="comment-area">
    <%= form_with(model: [@cafe, @comment], local: true) do |f| %>
      <%= f.text_area :text, class:"text-area" %>
      <%= f.file_field :image, class:"comment-image" %>
    <div class="action">
      <%= f.submit "コメントする", class:"comment-btn" %>
    </div>
    <% end %>
  </div>
</div>
<div class="all-comments">
  <% @comments.each do |comment| %>
    <li class="comments-list">
      <div class="comment-user">
        投稿者: <%= link_to comment.user.nickname, user_path(comment.user.id) %>
      </div>
      <div class="comment-text">
        <%= comment.text %>
      </div>
      <div class="comments-image">
        <%= image_tag comment.image.variant(resize: '300x300') if comment.image.attached? %>
      </div>
    </li>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Repos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-logo">
    <%= link_to "Repos", "/" %>
    <%= link_to image_tag("coffee.cup.png", class:"img"), "/" %>
  </div>

  <ul div class="header-lists">
    <% if user_signed_in? %>
      <li><%= link_to '新規投稿', new_cafe_path, class: "new-cafe" %></li>
      <li><%= link_to 'マイページ', user_path(@user.id), class: "user-page" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-in" %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_purpose.html.erb
<% unless params[:genre] == nil %>
  <%= form_with model: @cafes, class:"search-cafe", method: :get, local: true do |f| %>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"cafe-prefecture"}) %>
    <%= f. select(:purpose_id, {"#@purpose": @purpose_id}, {}, class:"purpose-select") %>
    <%= f.submit "検索", class:"select-btn" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="header">
  <div class="header-logo">
    <%= link_to "Repos", "/" %>
    <%= link_to image_tag("coffee.cup.png", class:"img"), "/" %>
  </div>

  <ul div class="header-lists">
    <% if user_signed_in? %>
      <li><%= link_to '新規投稿', new_cafe_path, class: "new-cafe" %></li>
      <li><%= link_to 'マイページ', user_path(current_user.id), class: "user-page" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-in" %></li>
    <% end %>
  </ul>
</div>

<%# cssは devise/registration/newを併用 %>
<%= form_with model: @users, url: user_path, class:"registrarion", method: :patch, local: true do |f| %>
  <div class="registration">
    <h2>編集画面</h2>

  <div class="form-group">
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">※必須</span>
      <div class="field">
        <%= f.text_field :nickname, value: current_user.nickname, class:"input-default" %>
  </div>
  <div class="form-group">
      <label class="form-text">Email</label>
      <span class="indispensable">※必須</span>
      <div class="field">
        <%= f.email_field :email, value: current_user.email, class:"input-default" %>
      </div>

  <div class="form-group">
      <label class="form-text">新しいパスワード(6文字以上)</label>
      <span class="indispensable">※必須</span>
      <div class="field">
    <%= f.password_field :password, class:"input-default", autocomplete: "new-password" %>
  </div>

     <div class="form-group">
      <label class="form-text">プロフィール</label>
      <span class="indispensable"></span>
      <div class="field">
        <%= f.text_area :profile, value: current_user.profile, class:"input-area-default" %>
      </div>

  <div class="actions">
    <%= f.submit "変更する", class:"submit" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="header">
  <div class="header-logo">
    <%= link_to "Repos", "/" %>
    <%= link_to image_tag("coffee.cup.png", class:"img"), "/" %>
  </div>

  <ul div class="header-lists">
    <% if user_signed_in? %>
      <li><%= link_to '新規投稿', new_cafe_path, class: "new-cafe" %></li>
      <li><%= link_to 'マイページ', user_path(current_user.id), class: "user-page" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-in" %></li>
    <% end %>
  </ul>
</div>

<div class="my-page">
  <% if current_user.id == @user.id %>
    <h2>マイページ</h2>
  <% else %>
    <h2>ユーザーページ<h2>
  <% end %>
  <div class="name-wrapper">
    <div class="name">
      <%= "名前" %>
    </div>
    <div class="user-profile">
      <%= @user.nickname %>
    </div>
  </div>
  <div class="name-wrapper">
    <div class="name">
      <%= "Email" %>
    </div>
    <div class="user-profile">
      <%= @user.email %>
    </div>
  </div>
  <div class="name-wrapper">
    <div class="name-profile">
      <%= "プロフィール" %>
    </div>
    <div class="profile">
      <%= @user.profile %>
    </div>
  </div>
  <% if current_user.id == @user.id %>
    <div class="edit-btn">
      <%= link_to "編集する",  edit_user_path(current_user), class:"cafe-edit" %>
    </div>
  <% end %>

  <% if @cafe.present? %>
  <div class="cafe-page">
    <h2>投稿したカフェ</h2>
    <div class="cafe-order">
    <% @cafe.each do |cafe| %>
      <div class="cafe-search">
        <%= link_to cafe_path(cafe) do %>
          <%= image_tag cafe.image, class:"search-image" %>
          <div class="search-name">
            『<%= cafe.name %>』
          </div>
          <div class="search-purpose">
          目的:  <%= cafe.purpose.name %>
          </div>
          <div class="search-region">
          地域:  <%= cafe.prefecture.name %>
          </div>
          <div class="search-address">
          住所:  <%= cafe.address %>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
  <% end %>
</div>